services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: lumen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  eurekaserver:
    build: ./eurekaserver
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8761/eureka/apps || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  clientes:
    build: ./clientes
    depends_on:
      eurekaserver:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lumen
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/

  cartoes:
    build: ./cartoes
    depends_on:
      eurekaserver:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lumen
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      SPRING_RABBITMQ_HOST: rabbitmq

  avaliador:
    build: ./avaliador
    depends_on:
      eurekaserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      SPRING_RABBITMQ_HOST: rabbitmq

  cloudgateway:
    build: ./cloudgateway
    ports:
      - "8080:8080"
    depends_on:
      eurekaserver:
        condition: service_healthy
      clientes:
        condition: service_started
      cartoes:
        condition: service_started
      avaliador:
        condition: service_started
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/

  rabbitmq:
    image: rabbitmq:4.3.5-management-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: lumen
      RABBITMQ_DEFAULT_PASS: lumen
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  rabbitmq_data:
