CREATE TABLE IF NOT EXISTS cartao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    bandeira VARCHAR(255),
    renda NUMERIC(38, 2),
    cor VARCHAR(255),
    limite_basico NUMERIC(38, 2)
);

CREATE TABLE IF NOT EXISTS cliente_cartao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf VARCHAR(255),
    id_cartao BIGINT,
    limite NUMERIC(38, 2),
    endereco_de_entrega VARCHAR(255),
    CONSTRAINT fk_cliente_cartao_cartao FOREIGN KEY (id_cartao) REFERENCES cartao (id),
    CONSTRAINT uk_cliente_cartao_cpf_cartao UNIQUE (cpf, id_cartao)
);
